name: flutter_elearning_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
# WebView Packages
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.14.0
  
  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE
  dio: ^5.4.0
  pin_code_fields: ^8.0.1
  app_links: ^6.4.0 
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  
  provider: ^6.1.2
  page_transition: ^2.1.0
  google_fonts: ^6.2.1
  form_validator: ^2.1.1
  shared_preferences: ^2.2.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  jwt_decoder: ^2.0.1
  universal_html: ^2.2.4
  http_parser: ^4.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  country_code_picker: ^3.2.0
  platform: ^3.1.6
  flutter_launcher_icons: ^0.14.3
  
  
  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.20.1
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#00A2FF" # Màu nền xanh
  image: assets/logos/studymate_logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/studymate_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/facebook.png
    - assets/google.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/logos/studymate_logo.png
    - assets/logos/studymate_icon.png

    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/content/


   #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800